cmake_minimum_required(VERSION 3.16)

add_executable(testes_validador TestesValidador.cpp)
target_link_libraries(testes_validador PRIVATE ensalamento_core)
add_test(NAME testes_validador COMMAND testes_validador)

add_executable(testes_alocador TestesAlocador.cpp)
target_link_libraries(testes_alocador PRIVATE ensalamento_core)
add_test(NAME testes_alocador COMMAND testes_alocador)